### ISSUE TITLE
Windows Installation 

### ISSUE THREAD

**Issue by mind-e-00** [dnote/dnote#218]
Have tried to install using the script installation but continue to get:

Please compile manually from https://github.com/dnote/dnote
A problem occurred while installing Dnote. Please report it on https://github.com/dnote/dnote/issues so that we can help you.

Could someone explain what must be done to get dnote up and running on Windows 10.

**Comment by sungwoncho** [comment]
Hi @mind-e-00, currently the installation script does not officially support Windows because it is written in bash. The script will say that your platform is not supported and exit. https://github.com/dnote/dnote/blob/92c3d8376e4229ddcef678f1cea2493969483404/pkg/cli/install.sh#L137-L138

You can download the Windows binary from https://github.com/dnote/dnote/releases, or compile the CLI manually.

**Comment by uktc01219** [comment]
Excuse me, sungwoncho, but there is no windows binary in the releases. Can you please elaborate about the windows support?

**Comment by sungwoncho** [comment]
@uktc01219 sorry for the confusion. The GitHub release tab contains both server and CLI releases. The Windows binary can be found for CLI releases. This is a bit confusing, and in the future we should have an official download page with clear distinction.
