### ISSUE TITLE
dnote vs standardnotes

### ISSUE THREAD

**Issue by jtagcat** [dnote/dnote#244]
Hey, could you compare yourself to [Standard Notes](https://standardnotes.org/)?

**Comment by sungwoncho** [comment]
@jtagcat from my cursory reading, I can summarize the comparison as follows:

Similarity:
- encrypted notebook using AES256 block cipher

Difference:
- The key generation and encryption are done differently. Cannot say for sure which is more secure.
- Standard Notes have mobile and desktop apps.
- Standard Notes have note title, tags, etc.

All in all, Standard Notes has more features and close to the our general notion of a note-taking app. Dnote is designed to jot down ideas and microlessons quickly without having to switch context too much.

I will close it for now because this is not an issue. Let's continue discussion further on https://forum.dnote.io if you want.
