### ISSUE TITLE
make install-js has hardcoded path

### ISSUE THREAD

**Issue by kimusan** [dnote/dnote#287]
## Environment

* project (cli, server, browser-extension):  all
* version:  0.2.0
* operating system:  Ubuntu linuz

## Description
The command "make install-js" to get the dependencies is using hard-coded path where it expects things to be. 
```
==> installing js dependencies
Makefile:40: recipe for target 'install-js' failed
/bin/sh: 1: cd: can't cd to /src/github.com/dnote/dnote/web
make: *** [install-js] Error 2
```

maybe make them relative as we always know the command is being ran in the root folder. 

## Steps to reproduce
place code in a folder not being /src/github.com/dnote/dnote and then run the command.

**Comment by sungwoncho** [comment]
Thanks for the detailed bug report. This is fixed by #272.

Old Go projects need to be in a predefined `GOPATH` directory, but in the case of your machine, `GOPATH` seems undefined. Therefore the following:

https://github.com/dnote/dnote/blob/cbfafb0a40ac3914d5e80d6f46932ed60dc5725b/Makefile#L47

evaluates to `/src/github.com/dnote/dnote/web`, producing that error.
