### ISSUE TITLE
Cryptic error when endpoint isn't pointing to valid url

### ISSUE THREAD

**Issue by jpalczewski** [dnote/dnote#441]
## Environment

* project (cli, server, browser-extension): cli
* version: dnote 0.11.0
* operating system: arch linux

## Description
While self-hosting, if you point to a wrong path(f.e. forgot `/api`) there's an error that doesn't suggest path problems in the first place during logging procedure:
`  ⨯ logging in: requesting session: decoding payload: invalid character '<' looking for the beginning of value `
(tbh my first thought was the idea that password with multiple special chars wasn't properly escaped somewhere, but intensive looking through docss suggested proper answer.

## Steps to reproduce
1. point cli to web app
2. try to login

**Comment by sungwoncho** [comment]
Thanks for taking time to report the issue with a detailed description. I have seen this behavior and it is indeed cryptic to the user.

The reason is that the Dnote server is responding with an HTML page that says something like "Not Found" when you hit a non-existing route (or depending on your reverse proxy setup, it might do that too). And we are trying to parse it like JSON:

https://github.com/dnote/dnote/blob/58a2b581aad2165f1119296581dd9c8759e61508/pkg/cli/client/client.go#L498-L500

We can probably add a check for 404 and display a custom message in the previous line. Something like:

https://github.com/dnote/dnote/blob/58a2b581aad2165f1119296581dd9c8759e61508/pkg/cli/client/client.go#L493-L495

Any ideas?

**Comment by sungwoncho** [comment]
Fixed in [v0.11.1](https://github.com/dnote/dnote/releases/tag/cli-v0.11.1). Thanks for taking time to file the issue.
