### ISSUE TITLE
Move configuration to XDG config directory

### ISSUE THREAD

**Issue by distefam** [dnote/dnote#478]
* **Please describe the feature you would like to have.**
Move Dnote configuration files to the [XDG config directory](https://wiki.archlinux.org/index.php/XDG_Base_Directory) according to the XDG specification.

* **What alternatives have you considered?**
Add a flag the the dnote command that takes a specified config file. This would allow users to make a dnote alias that passes a config file stored in the XDG base directory.

* **Any additional context**
Most linux programs these days have moved their configuration to the XDG config directory. Doing this makes managing one's dotfiles easier while maintaining a clean home directory.

**Comment by sungwoncho** [comment]
@distefam great idea. That way, we can stop putting stuff in users' home directories. How widespread is the adoption of that specification?

**Comment by sungwoncho** [comment]
Let us sit on it and collect more feedback.

**Comment by strogiyotec** [comment]
Here, any progress on it ? I also want to move my config to .config directory

**Comment by sungwoncho** [comment]
@strogiyotec I will have further look soon. Thanks for your patience.

**Comment by bresilla** [comment]
I am actually waiting for this too. Pretty much from my daily used apps only dnote's config are still left in $HOME.

The amazing thing of $XDG_CONFIG_HOME is that it falls back to $HOME/.config and lastly to $HOME directly. I didn't check for quite some time the specifications, but i think that if $XDG_CONFIG_HOME/dnote would be not found the fallback will be $HOME/.config/dnote and lastly to $HOME/.dnote (not sure how the dot before name works though)

Here is one of the packages that i recently used:
https://godoc.org/github.com/adrg/xdg

**Comment by sungwoncho** [comment]
Sorry for the delay. I am happy to ship it as an experiment. It might be some time before I can jump on to this one. Any PR is welcome.

Some thoughts:

* auto-migration of legacy `$HOME/.dnote` or leave it to the user?
* Is XDG platform independent? How does it work for linux/osx/windows? Do we need to handle them separately?

**Comment by bresilla** [comment]
XDG actually is just a specification. As far as i know, only Linux and BSD distros implement it.

- I think the proper way would be to first check the OS, if not MacOS or Windows then relay on XDG (so, only Linux and BSD left).

- Then the best way is to check if the DIR in `$XDG_DATA_HOME/dnote` exists, if so then use that otherwise fallback to check for `$HOME/.dnote`. Thus if users want to move to XDG then that has priority, if not then `$HOME/.dnote` would still work. If none of the DIRs exist, then that's a new user, and for new users use XDG by default.

**I maybe will have some time in some days, and I will try to implement it.**

One last thing though, i would rely on a third party library (as i mentioned before). Its a very light-wight lib (less than 100 lines of code actually).

**Comment by sungwoncho** [comment]
@bresilla @distefam quick question: what do you think about splitting configuration and data between `XDG_CONFIG_HOME` and `XDG_DATA_HOME`? For instance, `.dnoterc` configuration can go to the former, and `dnote.db` which is a sqlite file that stores the user data can go to the latter.

Doing so seems like a more proper way to follow the XDG base directory spec. On the other hand, doing so also might make it harder for users to find files by scattering them around.

**Comment by distefam** [comment]
Personally, I think that splitting up according to what you said is a better approach. For example, I back up my dotfiles via git and having them all together in the confit directory helps with this. Having the data separate let’s me encrypt and back up the data via a more generic and private backup mechanism.

**Comment by bresilla** [comment]
Actually, what you described is the preferred way. And most of Linux users already know that usually configs and databases are already split between most of their apps. Config has things that can easily be git based and public, while database is personal notes, thus separation is a good thing here. So I don't believe that you'll make it harder for the *nix users.


> Doing so seems like a more proper way to follow the XDG base directory spec, compared to putting everything in `XDG_CONFIG_HOME/dnote` On the other hand, doing so also might make it harder for users to find files by scattering them around.

**Comment by sungwoncho** [comment]
Released in [v0.12.0](https://github.com/dnote/dnote/blob/master/CHANGELOG.md#0120---2020-01-03). Please see the upgrade guide in the link.

Dnote will continue to use `~/.dnote` directory in the home directory, if one exists, for backward compatibility until the next major release. If the legacy directory does not exist, it will use `~/.local/share/dnote` for data and `~/.config/dnote` for configuration.

I left Windows to continue to use `~/.dnote` because XDG specification is not defined for Windows. Any suggestions, let me know.
