### ISSUE TITLE
Support syntax highlighting on CLI

### ISSUE THREAD

**Issue by distefam** [dnote/dnote#483]
* **Please describe the feature you would like to have.**

Since dnote now saves temp files with a markdown extension so that editors can have syntax highlighting (#163) it would be nice to have `view` able to syntax-highlight the output of the contents of a note.

* **What alternatives have you considered?**

I've created the following alias that pipes dnote's output to `glow`, which is a markdown formatter:

```sh
highlight_dnote_view() {
	dnote view "$1" | awk '/\-+content\-+/{f=1;next}f' | glow -
}
alias dv=highlight_dnote_view
```

* **Any additional context**

There are a variety of highlighting programs available. [Glow](https://github.com/charmbracelet/glow) is one dedicated to markdown. A simple shell variable like `DNOTE_HIGHLIGHT_PROGRAM=/usr/bin/glow` could be set by users and read by dnote to see if/how output should be highlighted. 

[Bat](https://github.com/sharkdp/bat) is another good one. Bat actually takes in lines to offset as a parameter so the above script could be rewritten to omit `awk`:

```sh
# starting from line 8 to skip header content
dnote view "$1" | bat --language md --line-range 8:
```

**Comment by sungwoncho** [comment]
Great idea. My initial thought is that syntax highlight should be done outside Dnote to avoid bloat. To assist with piping the output to syntax highlighting utilities, I can add `--content-only` flag to `view` so that we don't have to worry about skipping the header.

Usage would be:

```
dnote view 123 | glow -
```

What do you think?

**Comment by distefam** [comment]
This sounds sensible.

**Comment by sungwoncho** [comment]
An alternative would be to make `view` output content only by default, and add `--verbose` flag to output the frontmatter. Such design will make it even easier to pipe the output to various utilities. In addition, the output will be simple which aligns with the project's goal of being minimal.

On the other hand, it might break backward compatibility, if anyone is relying on the default behavior of outputting the frontmatter. Not sure if this change warrants a major version bump. Probably not because no API changes?

**Comment by sungwoncho** [comment]
[0.12.0](https://github.com/dnote/dnote/blob/master/CHANGELOG.md#0120---2020-01-03) adds `--content-only` flag for the `view` subcommand. If specified, it prints the content of the note only, skipping the frontmatter.

Now we can pass the content of a note to other utilities such as `glow` without `awk`. 

```
dnote v 288 --content-only | glow -
```

Thanks for the great feedback.
