### ISSUE TITLE
Browser add-in to add sites / web content to dnote

### ISSUE THREAD

**Issue by colearendt** [dnote/dnote#492]
* **Please describe the feature you would like to have.**

Evernote has a browser add-in that enables saving website content into a note directly. (Granted, it also supports rich content, which would be tricky in `dnote`). I think something similar would be useful for archiving website content and making it searchable.

- saves the website content directly to a new note in a configured default book (option to select book?)
- rich content?
- add the link to the website
- optionally just allow the selected text to be added
- even could allow popping up / adding in text to the note, directly from the browser.

* **What alternatives have you considered?**

Using Evernote's add-in and then copying the note into dnote.

* **Any additional context**

This could make it much easier to create notes directly from research rather than copying links from the browser and then opening up dnote in a terminal.

**Comment by sungwoncho** [comment]
Thanks for the suggestion. This could be a useful feature for the browser extension. It'd be difficult to support rich content (image, etc.) because Dnote doesn't support it (Just a thought: maybe we could store base64 encoding? How would that impact full-text search?)

I find myself using the browser extension less and less nowadays. Let us wait and collect more feedback on this idea.

**Comment by sungwoncho** [comment]
Now that the web client has been removed, this feature might be less relevant to the future roadmap. Therefore, I will close this. Please feel free to re-open.
