### ISSUE TITLE
darwin_arm64 cli binary is broken?

### ISSUE THREAD

**Issue by mzch** [dnote/dnote#623]
## Environment

* project (cli, server, browser-extension): cli
* version: dnote_0.13.0_darwin_arm64.tar.gz
* operating system: macOS 13.2 (Mac Studio M1 Ultra)

## Description
When executing `dnote` command, it always be killed.

## Steps to reproduce
1. Extact tar ball
2. type `./dnote`

**Comment by sungwoncho** [comment]
Thanks for reporting the issue. I tried to support macOS with M1 chip (#572) with #620 but it seems like it contained an issue. I will park darwin arm64 support for now because I currently do not have access to a mac to troubleshoot.

In the meantime, please try to build the CLI using the following command.

```
GOOS=darwin GOARCH=arm64 make version=0.1.0 build=cli
```

Go 1.20 is required.

Sorry for the inconvenience.

**Comment by mzch** [comment]
It works! Thanks @sungwoncho !

**Comment by sungwoncho** [comment]
No worries, forgot to mention that you might need `CGO_ENABLED=1`

```
GOOS=darwin GOARCH=arm64 make version=0.1.0 build=cli

**Comment by mzch** [comment]
Thanks @sungwoncho , but without `CGO_ENABLED` flag dnote-cli works. :)

**Comment by sungwoncho** [comment]
Cool. Just to confirm, are you using `dnote_0.14.0_darwin_arm64.tar.gz` from GitHub release?
